misc:
  #0 = No useless thing
  #1 = Just in console, when load
  #2 = Anything that can be useless !
  log-level: 0
message:
  message-head-added: '&a%s''s &aitem added in your inventory.'
skins:
  book_1:
    type: 'head'
    name: 'Nice Book'
    #RemoverTool can break it
    param:
      size: 'small'
      health: 1
      unbreakable: 1
      usable:
        #Number usable time
        time: 3
        #New Skin when empty ? (Skin name must be '*_empty.png')
        skinchange: 1
        #Automatic Reload in second ? 0 = Never / Max 300 (5min)
        reload: 0
        #Destruction when empty ? 0 = No
        destruction: 0
        #Message when using (Empty/remaining ...)?
        use_msg: 1
        #Custom message when descruction happen
        destruction_msg: "Oups, sorry ..."
        #When used, what it does ? (Heal 1 = Half Hearth)
        action: '{"heal": 1, "teleport": "1;2;3", "effect": "1/1/30;2/1/60;3/1/80", "msg": "May the force be with you ..."}'
        #choose one random action ?
        action_random: 1
  book_bible:
    type: 'head'
    name: 'Holy bible'
    param:
      size: 'normal'
      health: 10
      unbreakable: 0
  bowl_pasta:
    type: 'head'
    name: 'Pasta bowl'
    param:
      size: 'normal'
      health: 1
      unbreakable: 0
  calice:
    type: 'head'
    name: '&1Calice'
    param:
      size: 'block'
      health: 1
      unbreakable: 0
  crate_locked:
    type: 'head'
    name: 'Locked crate'
    param:
      size: 'block'
      health: 1
      unbreakable: 0